# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/FPGA/VGA/AX7010/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_axis_subset_converter_0_0/system_axis_subset_converter_0_0.xci
# IP: The module: 'system_axis_subset_converter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/FPGA/VGA/AX7010/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_axis_subset_converter_0_0/system_axis_subset_converter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axis_subset_converter_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: H:/FPGA/VGA/AX7010/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_axis_subset_converter_0_0/system_axis_subset_converter_0_0.xci
# IP: The module: 'system_axis_subset_converter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/FPGA/VGA/AX7010/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_axis_subset_converter_0_0/system_axis_subset_converter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axis_subset_converter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
