# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/Projects/Gen4/Gen4.srcs/sources_1/bd/gener4/ip/gener4_processing_system7_0_0/gener4_processing_system7_0_0.xci
# IP: The module: 'gener4_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Projects/Gen4/Gen4.srcs/sources_1/bd/gener4/ip/gener4_processing_system7_0_0/gener4_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gener4_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Xilinx/Projects/Gen4/Gen4.srcs/sources_1/bd/gener4/ip/gener4_processing_system7_0_0/gener4_processing_system7_0_0.xci
# IP: The module: 'gener4_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Projects/Gen4/Gen4.srcs/sources_1/bd/gener4/ip/gener4_processing_system7_0_0/gener4_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gener4_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
