# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/Linux14_1/Linux14_1.srcs/constrs_1/new/system.xdc

# Block Designs: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_axi_dynclk_0_0/system_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dynclk_0_0 || ORIG_REF_NAME==system_axi_dynclk_0_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_rgb2dvi_0_0/system_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_axis_subset_converter_0_0/system_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_subset_converter_0_0 || ORIG_REF_NAME==system_axis_subset_converter_0_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_axi_mem_intercon_0/system_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_0 || ORIG_REF_NAME==system_axi_mem_intercon_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_140M_0/system_rst_processing_system7_0_140M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_140M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_140M_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_processing_system7_0_axi_periph_0/system_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==system_processing_system7_0_axi_periph_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_100M_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_xlconstant_1_0/system_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_1_0 || ORIG_REF_NAME==system_xlconstant_1_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_xlconstant_2_0/system_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_2_0 || ORIG_REF_NAME==system_xlconstant_2_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_ps2_mouse_0_0/system_ps2_mouse_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps2_mouse_0_0 || ORIG_REF_NAME==system_ps2_mouse_0_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: E:/Linux14_1/Linux14_1.srcs/sources_1/bd/system/system_ooc.xdc
