# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/FPGA/S9miner_sample-master/P04_SD_BOOT/SD_BOOT.srcs/sources_1/bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xci
# IP: The module: 'zynq_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/FPGA/S9miner_sample-master/P04_SD_BOOT/SD_BOOT.srcs/sources_1/bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: H:/FPGA/S9miner_sample-master/P04_SD_BOOT/SD_BOOT.srcs/sources_1/bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xci
# IP: The module: 'zynq_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/FPGA/S9miner_sample-master/P04_SD_BOOT/SD_BOOT.srcs/sources_1/bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
