# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/FPGA/VGA/Gen4/Gen4.srcs/sources_1/bd/gener4/ip/gener4_v_tc_0_0/gener4_v_tc_0_0.xci
# IP: The module: 'gener4_v_tc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/FPGA/VGA/Gen4/Gen4.srcs/sources_1/bd/gener4/ip/gener4_v_tc_0_0/gener4_v_tc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'gener4_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: h:/FPGA/VGA/Gen4/Gen4.srcs/sources_1/bd/gener4/ip/gener4_v_tc_0_0/gener4_v_tc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gener4_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: h:/FPGA/VGA/Gen4/Gen4.srcs/sources_1/bd/gener4/ip/gener4_v_tc_0_0/gener4_v_tc_0_0.xci
# IP: The module: 'gener4_v_tc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/FPGA/VGA/Gen4/Gen4.srcs/sources_1/bd/gener4/ip/gener4_v_tc_0_0/gener4_v_tc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'gener4_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: h:/FPGA/VGA/Gen4/Gen4.srcs/sources_1/bd/gener4/ip/gener4_v_tc_0_0/gener4_v_tc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gener4_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
