# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/hdmi4.xdc

# Block Designs: bd/gener4/gener4.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gener4 || ORIG_REF_NAME==gener4} -quiet] -quiet

# IP: bd/gener4/ip/gener4_processing_system7_0_0/gener4_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gener4_processing_system7_0_0 || ORIG_REF_NAME==gener4_processing_system7_0_0} -quiet] -quiet

# IP: bd/gener4/ip/gener4_v_tpg_0_0/gener4_v_tpg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gener4_v_tpg_0_0 || ORIG_REF_NAME==gener4_v_tpg_0_0} -quiet] -quiet

# IP: bd/gener4/ip/gener4_ps7_0_axi_periph_0/gener4_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gener4_ps7_0_axi_periph_0 || ORIG_REF_NAME==gener4_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/gener4/ip/gener4_rst_ps7_0_40M_0/gener4_rst_ps7_0_40M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gener4_rst_ps7_0_40M_0 || ORIG_REF_NAME==gener4_rst_ps7_0_40M_0} -quiet] -quiet

# IP: bd/gener4/ip/gener4_v_axi4s_vid_out_0_0/gener4_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gener4_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==gener4_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/gener4/ip/gener4_v_tc_0_0/gener4_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gener4_v_tc_0_0 || ORIG_REF_NAME==gener4_v_tc_0_0} -quiet] -quiet

# IP: bd/gener4/ip/gener4_rgb2dvi_0_0/gener4_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gener4_rgb2dvi_0_0 || ORIG_REF_NAME==gener4_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/gener4/ip/gener4_auto_pc_0/gener4_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gener4_auto_pc_0 || ORIG_REF_NAME==gener4_auto_pc_0} -quiet] -quiet

# XDC: bd/gener4/gener4_ooc.xdc
